ARG BASE_IMAGE_VERSION

FROM tgbot_base:${BASE_IMAGE_VERSION}

WORKDIR /app

# ENV token="-token 7229787403:AAH0DVCx0wUQ-G9lkXYoIllHL0DhmdawEZo"

# Копируем файлы проекта 

COPY ./ /app

RUN /app/build.sh
