version: '3.8'

services:
  grpc_server:
    image: ${DOCKER_USERNAME}/grpc_server:${COMMON_IMAGES_VERSION}
    mem_limit: 4g
    mem_reservation: 2g
    ports:
      - "50051:50051"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]  # Временное решение для долгой инициализации
      start_period: 40m               # Увеличили до 10 минут
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  cursedwords_bot:
    image: ${DOCKER_USERNAME}/cwbot:${TARGET_IMAGES_VERSION}
    environment:
      - GRPC_SERVER_ADDRESS=grpc_server:50051o

    volumes:
      - ./bins/CursedWordsTGBot/Tests/FunctionalTests/Reactor_Tests:/tests  # Монтируем директорию с тестами
    command: /tests/reactor_tests  # Запуск тестов
    
    depends_on:
      - grpc_server

    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge