version: '3.8'

services:
  grpc_server:
    image: ${DOCKER_USERNAME}/grpc_server:${COMMON_IMAGES_VERSION}
    ports:
      - "50051:50051"
    networks:
      - app_network

  test_runner:
    image: ${DOCKER_USERNAME}/cwbot:${TARGET_IMAGES_VERSION}
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GRPC_SERVER_ADDRESS=grpc_server:50051
      - MESSAGES_FILE_PATH=/cwbot/bins/Tests/FunctionalTests/Reactor_Tests/messages.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    entrypoint: []
    command: >
      sh -c "
        echo 'Deleting webhook...';
        WEBHOOK_STATUS=$$(curl -s -w \"%{http_code}\" -X POST https://api.telegram.org/bot$${TELEGRAM_BOT_TOKEN}/deleteWebhook);
        if [[ \"$$WEBHOOK_STATUS\" != *\"200\"* ]]; then
          echo \"Failed to delete webhook. Status: $$WEBHOOK_STATUS\";
          exit 1;
        fi;
        # Шаг 1: Ожидание готовности gRPC сервера
        until python3 -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(1); exit(0 if s.connect_ex(('grpc_server', 50051)) == 0 else 1)\"; do
          echo 'Waiting for gRPC server...';
          sleep 1;
        done;
        /cwbot/bins/Tests/FunctionalTests/Reactor_Tests/reactor_tests
      "
    depends_on:
      - grpc_server
    networks:
      - app_network
    restart: "no"

networks:
  app_network:
    driver: bridge