version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: ./common_images_python/Dockerfile.python
    mem_limit: 4g
    mem_reservation: 2g
    ports:
      - "50051:50051"
    volumes:
      - ./server_grpc:/app/server_grpc
      - hf_cache:/root/.cache/huggingface/hub  # Используем именованный том
    healthcheck:
      test: ["CMD-SHELL", "exit 0"] # Всегда возвращает успех
      interval: 30s
      timeout: 30s
      start_period: 40m  # Увеличенный период ожидания
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

volumes:
  hf_cache:  # Именованный том для кэша

networks:
  app_network:
    driver: bridge