version: '3.8'

services:
  grpc_server:
    image: ${DOCKER_USERNAME}/grpc_server:${COMMON_IMAGES_VERSION}
    mem_limit: 4g
    mem_reservation: 2g
    ports:
      - "50051:50051"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]  # Временное решение для долгой инициализации
      start_period: 10m               # Увеличили до 10 минут
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  cursedwords_bot:
    image: ${DOCKER_USERNAME}/cwbot:${TARGET_IMAGES_VERSION}
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GRPC_SERVER_ADDRESS=grpc_server
      - MESSAGES_FILE_PATH=/cwbot/bins/Tests/FunctionalTests/Reactor_Tests/messages.txt    
      
    entrypoint: []  # Отключаем ENTRYPOINT из Dockerfile

    command: >
      sh -c "
      - "${TELEGRAM_BOT_TOKEN}"  

       find /cwbot/bins/Tests -name '*_tests' -type f -executable -print0 | xargs -0 -n1 sh -c

      "
    depends_on:
      - grpc_server
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge