version: '3.8'

services:
  grpc_server:
    image: ${DOCKER_USERNAME}/grpc_server:${COMMON_IMAGES_VERSION}
    ports:
      - "50051:50051"
    networks:
      - app_network
    restart: unless-stopped

  cursedwords_bot:
    image: ${DOCKER_USERNAME}/cwbot:${TARGET_IMAGES_VERSION}
    environment:
      - GRPC_SERVER_ADDRESS=grpc_server
      - MESSAGES_FILE_PATH=/cwbot/bins/Tests/FunctionalTests/Reactor_Tests/messages.txt
    networks:
      - app_network
    command: /cwbot/bins/Tests/FunctionalTests/Reactor_Tests/reactor_tests
    depends_on:
      - grpc_server
    restart: on-failure

networks:
  app_network:
    driver: bridge