FROM python:3.9-slim

# Установка зависимостей (все в одной RUN инструкции)
RUN apt-get update && apt-get install -y \
    procps \
    net-tools \
    telnet \
    git \
    netcat-openbsd \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем grpc_health_probe (отдельная RUN инструкция)
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.24 && \
    wget -qO /usr/local/bin/grpc_health_probe \
    https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /usr/local/bin/grpc_health_probe
WORKDIR /app

# Создаем директорию для кеша моделей
RUN mkdir -p /cache/huggingface

# Устанавливаем переменные окружения для кеширования
ENV HF_HOME=/cache/huggingface

# Копируем requirements.txt
COPY common_images_python/requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Загружаем модель и токенизатор на этапе сборки

RUN python -c "\
from transformers import AutoTokenizer, AutoModelForSequenceClassification; \
import os; \
os.environ['HF_HUB_DOWNLOAD_TIMEOUT'] = '600'; \
AutoTokenizer.from_pretrained('s-nlp/russian_toxicity_classifier', local_files_only=False); \
AutoModelForSequenceClassification.from_pretrained('s-nlp/russian_toxicity_classifier', local_files_only=False);"
# Копируем файлы сервера
COPY server_grpc/toxicity_classifier_pb2.py .
COPY server_grpc/toxicity_classifier_pb2_grpc.py .
COPY server_grpc/server.py .

# Дополнительная переменная для healthcheck (если нужно)
ENV GRPC_HEALTH_CHECK_SERVICE=""

CMD ["python3", "-u", "server.py"]