FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    procps \
    net-tools \
    telnet \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем requirements.txt из поддиректории
COPY common_images_python/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы сервера
COPY server_grpc/server.py .
COPY server_grpc/toxicity_classifier_pb2.py .
COPY server_grpc/toxicity_classifier_pb2_grpc.py .

CMD ["python3", "server.py"]