FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    procps \
    net-tools \
    telnet \
    && rm -rf /var/lib/apt/lists/*

# Создаем директорию для монтирования
RUN mkdir -p /app/server_grpc
WORKDIR /app/server_grpc

COPY ./common_images_python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Точка монтирования будет перезаписывать эту директорию
# Поэтому копируем только если файлы не монтируются
# COPY ./server_grpc /app/server_grpc

CMD ["python3", "server.py"]