name: CursedWords Bot CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jonnyrembo/cwbot_base:1.0
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        COMMON_IMAGES_VERSION: "1.0"
        TARGET_IMAGES_VERSION: "1.0"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Verify build script
        run: |
          ls -la
          test -f build-local.sh || (echo "build-local.sh not found"; exit 1)
          chmod +x build-local.sh

      - name: Build project
        run: |
          ./build-local.sh

      - name: Run all unit tests
        run: |
          cd build
          ctest --output-on-failure --verbose

      - name: Start infrastructure and run functional tests
        run: |
            # Перейти в рабочую директорию CI
            cd $GITHUB_WORKSPACE
            
            # Запускаем с принудительным монтированием
            docker-compose -f docker-compose.yml run \
              --rm \
              -v /github/workspace:/app \
              test_runner

      # - name: Start infrastructure and run functional tests
      #   run: |
      #     docker-compose -f docker-compose.yml up -d
      #     docker-compose -f docker-compose.yml run --rm test_runner
      #     docker-compose -f docker-compose.yml down