name: TGBot Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Для Ubuntu, но можно выбрать другие операционные системы

    steps:
      # Шаг 1: Проверяем исходный код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка зависимостей (если они есть)
      - name: Install dependencies
        run: |
          apt-get update && apt-get upgrade -y && \
          apt-get install -y build-essential g++ make cmake libcurl4-openssl-dev libssl-dev libjsoncpp-dev git zlib1g-dev

          apt-get install -y libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev

          apt-get install -y libgtest-dev

          mkdir tgbot-cpp

          cd tgbot-cpp

          git clone https://github.com/reo7sp/tgbot-cpp
          cmake . && \
          make -j4 && \
          make install

      # Шаг 3: Создаем директорию для сборки
      - name: Create build directory
        run: mkdir build

      # Шаг 4: Запуск CMake для конфигурации проекта
      - name: Configure project with CMake
        run: |
          cd build
          cmake ..

      # Шаг 5: Компиляция проекта
      - name: Build project
        run: |
          cd build
          make

      # Шаг 6: Запуск тестов (если они есть)
      - name: Run tests
        run: |
          cd build/Tests/UnitTests/
          ./Parser_Tests/parser_tests*
          ./Queue_Tests/queue_tests*
          ./SignalHandler_Tests/signalhandler_tests*
          ./ThreadSafeQueue_Tests/threadsafequeue_test*
